# Auto-generated R script to convert PPTX to Quarto
output_file <- 'working_with_strings.qmd'
yaml_header <- '---\ntitle: "Working with Strings"\nformat: xaringan::moon_reader\ncss: ["xaringan-themer.css", "slides.css"]\nlib_dir: libs\nnature:\n  ratio: "16:9"\n  highlightLines: true\n  highlightStyle: solarized-light\n  countIncrementalSlides: false\n  chalkboard: true\n---\n\n'
slides <- list(
  '## Slide 1\nData WranglingWorking with Strings\nSTAT 7500 – Statistical Programming',
  '## Slide 2\nOverview of Data Wrangling\nIsolating data – filter, select, and arrange\nPiping operator – %>%\nDeriving information – summarize, group_by, mutate\nCombining datasets – bind_row and joins\nTidy data – pivot_longer, pivot_wider\nWorking with strings – stringr\nScraping data – rvest',
  '## Slide 3\nWorking with Strings\nstringr package (in tidyverse)\n\nwww.gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf\n![Image placeholder for 1 image(s) on slide 3]',
  '## Slide 4\nReading in Character Strings from Files\nread_file() reads in the entire file as a single character string\nread_lines() creates a vector of character strings, each one from the \n	file is a separate line',
  '## Slide 5\nChanging the Case\nstr_to_lower(x),str_to_upper(x), str_to_title(x) and str_to_sentence(x)\nExamples:\n	str_to_lower(“Villanova”)\n	str_to_upper(state.name)\n![Image placeholder for 2 image(s) on slide 5]',
  '## Slide 6\nstr_sub (stringr) or substr (base)\nstr_sub(string,start,end)\n	note: negative numbers count from the end\nstr_sub("Villanova",1,1) 		# extracts the first value\nstr_sub("Villanova",6,9) 		# extracts our nickname\nstr_sub("Villanova",6)		# another version (6 to end)\nstr_sub("Villanova",-4)		# another version (4th from end)\nstr_sub(state.name,1,3)\nAnother option:\n	abbreviate(state.name)\nSubstrings\n![Image placeholder for 4 image(s) on slide 6]',
  '## Slide 7\nFind Character Strings\nstr_which(vector, pattern)  [base::grep] identifies the indices of matches\nstr_which(c(“Aardvark”,”Anteater”,”Alligator”),”k”)   =>   1\nstr_subset() identifies the values of matches [base::grep(value=T)]\nstr_subset(c(“Aardvark”,”Anteater”,”Alligator”),”k”)   =>   “Aardvark”\nstr_detect() produces logical vector instead of count [base::grepl]\nUseful for using with mutate or other functions that require vectors\nstr_detect(c(“Aardvark”,”Anteater”,”Alligator”),”k”)   =>   T  F  F\nSeries of characters\nYou can use “[]” to identify series of characters\nYou can use “-” within “[]” to identify related characters\nstr_detect(c(“Aardvark”,”Anteater”,”Alligator”),”[gk]”)   =>   T  F  T',
  '## Slide 8\nFind Character Strings II\nstr_which(state.name,”V”)  # lists all states with a V in it\n			# actually, it lists the index\nstr_subset(state.name,”V”)\n			# Hey, what happened to Pennsylvania?\nstr_subset(str_to_upper(state.name),”V”)\n\nstr_subset(state.name,”[Vv]”)  # searches for “V” or “v”\n![Image placeholder for 4 image(s) on slide 8]',
  '## Slide 9\nFind and Replace\nstr_replace(string, pattern, replacement)  # replaces first occurrence\nstr_replace_all(string, pattern, replacement)  # replaces all occurrences\nTo remove spaces from state names,\n	states_nospace <- str_replace_all(state.name, “ “, “”)\n\n\n\n\nBetter yet, you can use str_remove_all(state.name,” “) instead…\n![Image placeholder for 1 image(s) on slide 9]',
  '## Slide 10\nCounting String Occurrence\nstr_count(string,pattern)\nstr_count(“pneumonoultramicroscopicsilicovolcanoconiosis”,”[aeiou]”)\nfruit <- c("apple", "banana", "pear", "pineapple")\nstr_count(fruit, "a")\nhas_ss <- str_count(str_to_lower(state.name),"ss")   # what is this asking for?\nstate.name[has_ss>0]\nstate.name[has_ss>1]\nstr_count(read_file("https://en.wikipedia.org/wiki/Villanova_University"),"Villanova")\n	The word “Villanova” appears 613 times\n![Image placeholder for 4 image(s) on slide 10]',
  '## Slide 11\nPaste (Concatenate)\npaste("Pi is ",pi)\npaste("Pi is about",round(pi,5))\npaste("Pi=",pi)\npaste("Pi=",pi,sep="")\npaste0("Pi=",pi)  # shortcut for paste with sep=“”\n\n# For different length vectors, you can combine values\npaste("MAT",1:5,sep="-")\n![Image placeholder for 2 image(s) on slide 11]',
  '## Slide 12\nUsing Paste in Titles\nlabs(subtitle=paste("Correlation=",\n	round(cor(badinc$avginc,badinc$badavginc),4)))\n![Image placeholder for 1 image(s) on slide 12]',
  '## Slide 13\nMeta-characters\nstring <- c("$20.00", "$40")\nstr_remove_all(string,"$")\n	“$20.00”     “$40”\nstr_remove_all(string,“\\$")\n	“20.00”     “40”\n![Image placeholder for 1 image(s) on slide 13]',
  '## Slide 14\nCharacter Classes\nRegular expressions (regex)\nAre patterns describing text\n^ is a negating qualifier\n![Image placeholder for 1 image(s) on slide 14]',
  '## Slide 15\nAnchor Sequences\nExamples:\nstr_replace_all("the dandelion war of 	2010“, "\\d", "_")\n     “the dandelion war of ____”\nmyword <- “t e s t i f y”\nprint(“Let’s play hangman…”)\nstr_replace_all(myword,”\\w”,”_”)\n	Let’s play hangman…\n	_ _ _ _ _ _ _\n(person guesses “t”)\nstr_replace_all(myword,"[^t\\s]","_")\n	t _ _ t _ _ _ \n(person guesses “e”)\nstr_replace_all(myword,"[^te\\s]","_")\n	t e _ t _ _ _\n![Image placeholder for 1 image(s) on slide 15]',
  '## Slide 16\nQuantifiers\nstr_subset(state.name,”e”)\n		Connecticut  Delaware  Georgia, etc.\nstr_subset(state.name,”e{2,}”)   # Looks for 2 e’s in a row…\n		Tennessee\n![Image placeholder for 1 image(s) on slide 16]',
  '## Slide 17\nYour Turn\nChoose five people’s names and enter them into a vector\nExtract the first three characters of each name\nCombine the first and last letter of name into a character string (of length 2)\nCreate two variables\ni)    the number of vowels in each person’s name\nii)   the proportion of vowels in each person’s name\nGraph these variables by name\nChoose any website and identify the number of times a specific word appears on it [Note – you likely want to save the file as text first]\nUse the babynames dataset to…\nplot n over time by name for girls whose name starts with “Elizab” but isn’t “Elizabeth”\nHow many unique names are there that contain the string “liz”\nExplore derivations of your own name',
  '## Slide 18\nYour Turn Solutions\n# a\nsmithposners <- c("Michael","Wendy","Yael","Jonah","Ari")\n# b\nstr_sub(smithposners,1,3)\n#c\npaste0(str_sub(smithposners,1,1),str_sub(smithposners,-1))\n# d\nspv0 <- str_count(smithposners,"[aeiou]")\nspv <- str_count(str_to_lower(smithposners),"[aeiou]")\nspv[spv==0] <- str_count(str_to_lower(smithposners),"y")\nsps <- data.frame(names=smithposners, spv)\nggplot(sps) + geom_col(aes(reorder(names,desc(spv)),spv), fill=“blue”)\nsps <- mutate(sps, spvp = spv / str_length(names))\nggplot(sps) + geom_col(aes(reorder(names,desc(spvp)),spvp), fill=“blue”)\n![Image placeholder for 4 image(s) on slide 18]',
  '## Slide 19\nYour Turn Solutions\n![Image placeholder for 2 image(s) on slide 19]',
  '## Slide 20\nYour Turn - Solutions\nbabynames %>% \n  filter(sex=="F",\n     	str_sub(name,1,6)=="Elizab",\n     	name != "Elizabeth") %>% \n  ggplot() + geom_line(aes(x=year,\n	y=n,color=name))\n![Image placeholder for 1 image(s) on slide 20]',
  '## Slide 21\nYour Turn Solutions\n# f ii)\nbabynames %>%  \n  filter(str_detect(name,"liz")) %>% \n  count(name) %>% \n  nrow()\nbabynames %>% \n  filter(str_detect(str_to_lower(name),"liz")) %>% \n  count(name) %>% \n  nrow()\n![Image placeholder for 2 image(s) on slide 21]',
  '## Slide 22\nYour Turn - Solutions\n# f iii)\nbabynames %>%\n   mutate(michael_type = case_when(\n	name=="Michael" & sex=="M" ~ "Michael_M",    \n	name=="Michael" ~ "Michael_F",    \n	str_sub(name,1,7) == "Michael" ~ "Michael_Other")) %>%  \n   group_by(year, michael_type, sex) %>%   \n	summarize(total = sum(n), \n		.groups = "drop") %>%\n    drop_na(michael_type)\n![Image placeholder for 1 image(s) on slide 22]',
  '## Slide 23\nYour Turn - Solutions\n# f iii) geom_line(aes(x=year,y=total,lty=sex,color=michael_type))\n	+  scale_y_log10(breaks = 10^(1:5), labels = paste0("10^",1:5))\n![Image placeholder for 2 image(s) on slide 23]',
  '## Slide 24\n![Image placeholder for 1 image(s) on slide 24]',
  '## Slide 25\nWorking with Text\nDownload Villanova’s Mission Statement text file from website\nIt matters whether you save it as an html file or text file\nOriginal is at https://www1.villanova.edu/villanova/president/about_university/mission.html \nI copied it to Word and saved it as a text file… (with more skill, you can remove all the hypertext codes)\nmission <- read_file("Villanova Mission Statement.txt")',
  '## Slide 26\nTokenization (Parsing the File by Word)\nmission %>% str_split(" ")  # split on each space\n\n\n\n\nmission %>% str_split("\\s+") # split on 1+ space, incl \n and \r\n![Image placeholder for 2 image(s) on slide 26]',
  '## Slide 27\nTokenization II\nmission %>% str_split("\\s+") %>% .[[1]]    # first item in list\nmission %>% str_split("\\s+") %>% unlist()   # unlists in data.frame\n\n\n\nmission %>% str_remove_all("[[:punct:]]") %>% \n	str_split("\\s+") %>% unlist() %>% 	str_to_lower()\n![Image placeholder for 2 image(s) on slide 27]',
  '## Slide 28\nTokenization III\nmissionwords <- mission %>% \n	str_remove_all("[[:punct:]]") %>% 	# remove punctuation* \n	str_split("\\s+") %>% 			# splits on spaces +\n	unlist() %>% 				# make into data.frame\n	str_to_lower() %>%			# makes lower case\n	data.frame(words=.)		 	# add this to make data.frame\n			* different result if you put this before unlist.  Why?\nmissionwords %>% nrow()\nmissionwords %>% n_distinct(words)\nTechnically, “tokenizing” then assigns each word to a number\n![Image placeholder for 2 image(s) on slide 28]',
  '## Slide 29\nWord Totals\nmissionwords %>% \n   count(words) %>% \n   arrange(desc(n))\n![Image placeholder for 1 image(s) on slide 29]',
  '## Slide 30\nStopwords\nlibrary(tm)\nstopwords("english")\n![Image placeholder for 1 image(s) on slide 30]',
  '## Slide 31\nRemove Stopwords\nmissionwords %>% \n   filter(words %in% stopwords("english") == F) %>% \n   count(words) %>% \n   arrange(desc(n))\n![Image placeholder for 1 image(s) on slide 31]',
  '## Slide 32\nGraph of Mission Statement Words\nmissionwords %>% \n   filter(words %in% stopwords("english") == F) %>% \n   count(words) %>% \n   arrange(desc(n)) %>% \n   filter(n>=3) %>%\n   ggplot() +\n   geom_col(aes(words,n))\n![Image placeholder for 1 image(s) on slide 32]',
  '## Slide 33\nGraph of Mission Statement Words II\nmissionwords %>% \n   filter(words %in% stopwords("english") == F) %>% \n   count(words) %>% \n   arrange(desc(n)) %>% \n   filter(n>=3) %>%\n   ggplot() +\n   geom_col(aes(reorder(words,n),\n	n,fill=n)) +\n   coord_flip() +\n   labs(y="word", x="freq") + \n   guides(fill=F)\n![Image placeholder for 1 image(s) on slide 33]',
  '## Slide 34\nWordcloud\nThere’s a package for that…\nwordcloud(missionwords$words)\n![Image placeholder for 2 image(s) on slide 34]',
  '## Slide 35\nWordcloud II\nwordcloud(missionwords$words, \n	min.freq=4, colors=1:4, random.order=F)\n![Image placeholder for 1 image(s) on slide 35]',
  '## Slide 36\nAdditional Topics in Text Mining\nEmotion and Sentiment Classification\nNatural Language Processing (NLP)\nCorpora – see tm package\nStatistics for Text Mining',
  '## Slide 37\nPractice with Text\nThe gutenbergr package links to data from the Gutenberg Project\n\n\n\n\nChoose a topic to explore\nCreate an indicator variable if it is mentioned in the title\nExplore it further…\n![Image placeholder for 1 image(s) on slide 37]',
  '## Slide 38\njanitor::clean_names()\nChanges all variable names to valid R names with common format\n![Image placeholder for 4 image(s) on slide 38]',
  '## Slide 39\nOn Shakespeare We Count\nThis Photo by Unknown Author is licensed under CC BY-SA\n![Image placeholder for 1 image(s) on slide 39]',
)

# Write to .qmd file
writeLines(c(yaml_header, slides), output_file)
