---
title: "Working with Strings"
author: "Dr. Katie Fitzgerald, adapted from Dr. Michael Posner"
output:
  xaringan::moon_reader:
    css: ["xaringan-themer.css", "slides.css"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
    chalkboard: true
---

```{r child = "setup.Rmd"}
```

## Data Wrangling
Working with Strings  
STAT 7500 – Statistical Programming

---

## Overview of Data Wrangling
- Isolating data – filter, select, and arrange
- Piping operator – %>%
- Deriving information – summarize, group_by, mutate
- Combining datasets – bind_row and joins
- Tidy data – pivot_longer, pivot_wider
- Working with strings – stringr
- Scraping data – rvest

---

## Working with Strings
stringr package (in tidyverse)  
[Handling and Processing Strings in R](http://www.gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf)  
![Image placeholder]

---

## Reading in Character Strings from Files
```r
read_file()    # reads entire file as single string
read_lines()   # creates vector of strings, each line separate
```

---

## Changing the Case
```r
str_to_lower(x)
str_to_upper(x)
str_to_title(x)
str_to_sentence(x)

# Examples:
str_to_lower("Villanova")
str_to_upper(state.name)
```
![Image placeholder]

---

## Substrings
```r
str_sub(string, start, end)  # negative numbers count from end
str_sub("Villanova", 1, 1)   # extracts first value
str_sub("Villanova", 6, 9)   # extracts nickname
str_sub("Villanova", 6)      # from 6 to end
str_sub("Villanova", -4)     # 4th from end
str_sub(state.name, 1, 3)

# Another option:
abbreviate(state.name)
```
![Image placeholder]

---

## Find Character Strings
```r
str_which(vector, pattern)      # indices of matches
str_subset(vector, pattern)     # values of matches
str_detect(vector, pattern)     # logical vector

# Examples:
str_which(c("Aardvark","Anteater","Alligator"),"k")  # => 1
str_subset(c("Aardvark","Anteater","Alligator"),"k") # => "Aardvark"
str_detect(c("Aardvark","Anteater","Alligator"),"k") # => T F F
```

---

## Find Character Strings II
```r
str_which(state.name,"V")
str_subset(state.name,"V")
str_subset(str_to_upper(state.name),"V")
str_subset(state.name,"[Vv]")
```
![Image placeholder]

---

## Find and Replace
```r
str_replace(string, pattern, replacement)      # first occurrence
str_replace_all(string, pattern, replacement)  # all occurrences

# Remove spaces:
states_nospace <- str_replace_all(state.name, " ", "")
# Or better:
str_remove_all(state.name, " ")
```
![Image placeholder]

---

## Counting String Occurrence
```r
str_count(string, pattern)
str_count("pneumonoultramicroscopicsilicovolcanoconiosis","[aeiou]")

fruit <- c("apple","banana","pear","pineapple")
str_count(fruit,"a")

has_ss <- str_count(str_to_lower(state.name),"ss")
state.name[has_ss > 0]
state.name[has_ss > 1]

str_count(read_file("https://en.wikipedia.org/wiki/Villanova_University"),"Villanova")
# The word “Villanova” appears 613 times!
```
![Image placeholder]

---

## Paste (Concatenate)
```r
paste("Pi is ", pi)
paste("Pi is about", round(pi,5))
paste("Pi=", pi)
paste("Pi=", pi, sep="")
paste0("Pi=", pi)  # shortcut

# Combine values:
paste("MAT", 1:5, sep="-")
```
![Image placeholder]

---

## Using Paste in Titles
```r
labs(subtitle = paste("Correlation=", round(cor(badinc$avginc,badinc$badavginc),4)))
```
![Image placeholder]

---

## Meta-characters
```r
string <- c("$20.00", "$40")
str_remove_all(string, "$")      # wrong
str_remove_all(string, "\$")  # correct
```
![Image placeholder]

---

## Character Classes
Regular expressions (regex) describe text patterns  
^ negates  
POSIX classes exist  
![Image placeholder]

---

## Anchor Sequences
```r
str_replace_all("the dandelion war of 2010", "\d", "_")
# => "the dandelion war of ____"

myword <- "t e s t i f y"
str_replace_all(myword,"\w","_")  # hangman
str_replace_all(myword,"[^t\s]","_")
str_replace_all(myword,"[^te\s]","_")
```
![Image placeholder]

---

## Quantifiers
```r
str_subset(state.name,"e")
str_subset(state.name,"e{2,}")  # Looks for 2 e’s in a row
# => Tennessee
```
![Image placeholder]

---

## Your Turn
- Choose five names and enter into a vector
- Extract first three characters
- Combine first and last letter
- Count vowels and proportion
- Graph these variables
- Scrape a website and count word occurrences
- Use babynames dataset for name analysis

---

## Your Turn Solutions
```r
smithposners <- c("Michael","Wendy","Yael","Jonah","Ari")
str_sub(smithposners,1,3)
paste0(str_sub(smithposners,1,1),str_sub(smithposners,-1))
spv <- str_count(str_to_lower(smithposners),"[aeiou]")
sps <- data.frame(names=smithposners, spv)
ggplot(sps) + geom_col(aes(reorder(names,desc(spv)),spv), fill="blue")
```
![Image placeholder]

---

## Working with Text
Download Villanova’s Mission Statement  
[Mission Statement](https://www1.villanova.edu/villanova/president/about_university/mission.html)  
```r
mission <- read_file("Villanova Mission Statement.txt")
```

---

## Tokenization
```r
mission %>% str_split(" ")
mission %>% str_split("\s+")
```
![Image placeholder]

---

## Tokenization II
```r
mission %>% str_split("\s+") %>% unlist()
mission %>% str_remove_all("[[:punct:]]") %>% str_split("\s+") %>% unlist() %>% str_to_lower()
```
![Image placeholder]

---

## Word Totals
```r
missionwords %>% count(words) %>% arrange(desc(n))
```
![Image placeholder]

---

## Stopwords
```r
library(tm)
stopwords("english")
```
![Image placeholder]

---

## Remove Stopwords
```r
missionwords %>% filter(words %in% stopwords("english") == F) %>% count(words) %>% arrange(desc(n))
```
![Image placeholder]

---

## Graph of Mission Statement Words
```r
missionwords %>% filter(words %in% stopwords("english") == F) %>% count(words) %>% arrange(desc(n)) %>% filter(n>=3) %>% ggplot() + geom_col(aes(words,n))
```
![Image placeholder]

---

## Wordcloud
```r
wordcloud(missionwords$words, min.freq=4, colors=1:4, random.order=F)
```
![Image placeholder]

---

## Additional Topics
- Emotion and Sentiment Classification
- NLP
- Corpora (tm package)
- Statistics for Text Mining

---

## Practice with Text
[gutenbergr](https://cran.r-project.org/web/packages/gutenbergr/index.html)  
Explore topics from [Gutenberg Project](https://www.gutenberg.org/)

---

## janitor::clean_names()
Changes all variable names to valid R names with common format  
![Image placeholder]

---

## On Shakespeare We Count!
[William Shakespeare quotes about life](https://en.wikiquote.org/wiki/William_Shakespeare_quotes_about_life)  
![Image placeholder]
